# Generated by Django 4.1.2 on 2023-01-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_options_alter_recipe_title'),
        ('recipes', '0005_alter_recipe_tags'),
    ]

    operations = [
    ]
